default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: changed_development

test:
  <<: *default
  database: changed_test

test:
  <<: *default
  database: changed_production
