version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1
jobs:
  build:
    docker:
      -
        image: circleci/ruby:2.6.6
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 4
          BUNDLE_PATH: vendor/bundle
          BUNDLER_VERSION: 2.1.4
          RAILS_ENV: test
          RACK_ENV: test
          PGHOST: localhost
      -
        image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: playground_test

    steps:
      - checkout

      # bundler
      - ruby/install-deps:
          bundler-version: 2.1.4

      # postgres
      - run: dockerize -wait tcp://localhost:5432

      # database
      - run: bundle exec rake db:create db:schema:load

      # rubocop
      - run: bundle exec rubocop --format progress --format html --out tmp/rubocop.html

      # brakeman
      - run: bundle exec brakeman -z --format html --output tmp/brakeman.html

      # rspec
      - run: bundle exec rspec --format progress --format RspecJunitFormatter --out tmp/rspec/rspec.xml

      # results
      - store_test_results:
          path: tmp/rspec

      # artifacts
      - store_artifacts:
          path: coverage
          destination: coverage

      - store_artifacts:
          path: tmp/rubocop.html
          destination: rubocop.html

      - store_artifacts:
          path: tmp/brakeman.html
          destination: brakeman.html
